baseurl: /cv
destination: ../cv
title: "@vcampitelli"
description: "my online cv"
plugins:
  - jekyll-multiple-languages-plugin
exclude: ['build.sh', 'Dockerfile']

# jekyll-multiple-languages-plugin
languages: ["pt", "en"]
exclude_from_localizations: ["img", "css"]
